apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: i5g3ogm3r-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: i5g3ogm3r-go 
  name: i5g3ogm3r-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: i5g3ogm3r-go 
